### ISSUE TITLE
Tidy up and dry up code

### ISSUE THREAD

**Issue by broccolini** [primer/primer.style#11]
Lots of tidying to do. Top of mind are:

- [x] pull lef/right text/image grid into it's own component since spacing is the same
- [ ] make a media object component for icons + text such as packages and octicons
- [x] remove classNames and swap out for primer-react components
- [x] remove redundant code (old components, packages etc.)
- [ ] move react logo into custom octicon component
- [ ] check accessibility

**Comment by emplums** [comment]
@broccolini I started working on replacing some of the extended Link components with plain Link components since we've now got typography system props in primer/components... one thing I ran into was not being able to access all of our typography theme values (such as `mono` from `fonts`, to be used with the styled-system `fontFamily` props).

What do you think about using the `primer/components` theme in primer.style instead of what we've got in primer.style now (a few imports from primitives + the default theme values from styled system)? I think it makes sense to build this site with the theme we're shipping with `primer/components` but not sure if there's any reason in particular that you stuck with imports from primitives? The only hitch I'm seeing is that we'll need to rework a bunch of the spacing since the default breakpoints + spacing values from styled-system are pretty different from our values shipped with `primer/components`. Let me know what you think!

**Comment by broccolini** [comment]
This is now outdated.
