### ISSUE TITLE
Docked version of SideNav component?

### ISSUE THREAD

**Issue by edokoa** [primer/primer.style#194]
I'm working with Insights helping them pick Primer components and I can't find a docked SideNav component. There is a SideNav in Primer.style, but it seems to be a floating menu (both in components and CSS). @broccolini pointed out it exists, but it's not in the live docs.

**Floating version**

![image](https://user-images.githubusercontent.com/694831/79247028-3e9fee80-7e7a-11ea-9635-25ecb58c464e.png)

**Docked version (Figma screenshot)**

![image](https://user-images.githubusercontent.com/694831/79247241-8f174c00-7e7a-11ea-8a43-d2e9a89878d7.png)

**Comment by BinaryMuse** [comment]
@edokoa Is the only difference the border radius? Since `SideNav` gets [BORDER system props](https://primer.style/components/SideNav#system-props), you could do something like this:

```javascript
<SideNav bordered borderRadius={0} maxWidth={300} aria-label="Main">
  <SideNav.Link href="#url">
    <StyledOcticon mr={2} size={16} icon={Zap} />
    <Text>Overview</Text>
  </SideNav.Link>
  <SideNav.Link href="#url" selected>
    <StyledOcticon mr={2} size={16} icon={Octoface} />
    <Text>Key metrics</Text>
  </SideNav.Link>

  <SideNav bordered variant="lightweight" py={3} pl={6} backgroundColor="white">
    <SideNav.Link href="#url">
      <Text>Code review turnaround</Text>
    </SideNav.Link>
    <SideNav.Link href="#url">
      <Text>Time to open</Text>
    </SideNav.Link>
    <SideNav.Link href="#url">
      <Text>Pull request size</Text>
    </SideNav.Link>
    <SideNav.Link href="#url" selected>
      <Text>Work in progress</Text>
    </SideNav.Link>
    <SideNav.Link href="#url">
      <Text>Code review distribution</Text>
    </SideNav.Link>
  </SideNav>

  <SideNav.Link href="#url">
    <StyledOcticon mr={2} size={16} icon={Search} />
    <Text>Reports</Text>
  </SideNav.Link>
  <SideNav.Link href="#url">
    <StyledOcticon mr={2} size={16} icon={Person} />
    <Text>Settings</Text>
  </SideNav.Link>
</SideNav>
```

![image](https://user-images.githubusercontent.com/189606/79253091-83566600-7e37-11ea-84c9-6e8be84d1881.png)

(I used random icons because they're not all available in the live editor)

**Comment by edokoa** [comment]
Thank you so much! ^_^

**Comment by edokoa** [comment]
From your screenshot it looks like the panel is now docked to the left. For me the main difference is that the current nav menus seem to be floating, and the docked menu would be docked to the left of the screen?

Is this a matter of the top container being 100% width vs not and it will always stick to the left of the parent? (I didn't use Primer so much)

**Comment by BinaryMuse** [comment]
@edokoa `SideNav` doesn't have any margin by default. On the primer.style site, the live code containers have a 16 pixel padding, which may be what's giving it the floating impression. With it removed the `SideNav` will bump up against its container.

![image](https://user-images.githubusercontent.com/189606/79488898-550b8e80-7fcf-11ea-9a42-8a14ef2e9e2e.png)

In the screenshot above, you can see that the entire example (including the black box above the `SideNav`) appears to be floating because of the same container padding.

**Comment by BinaryMuse** [comment]
Chatted with @edokoa and I think this can be closed ✨
